# Generated by Django 3.2.4 on 2021-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210708_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='genr',
        ),
    ]
