# Generated by Django 3.2.4 on 2021-07-10 17:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210708_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10),
        ),
    ]
